### ISSUE TITLE
utf iterator comparison issue

### ISSUE THREAD

**Issue by dboer** [BenHanson/lexertl#15]
For this example I am using utf-8.
I am trying to make the utf iterator stop before certain code point. When utf-8 characters have different lengths this doesn't seem to work. The iterators uStart  and uEnd will never be the same because of the internal state of the iterator.

	std::u32string asianToken;
	asianToken.push_back(0x2E80);

	typedef lexertl::basic_utf8_out_iterator<const char32_t*> Utf8OutputIterator;
	const char32_t *begin = asianToken.data(), *end = asianToken.data() + asianToken.length();
	Utf8OutputIterator outBegin(begin, end), outEnd(end, end);

	std::string asianText;
	std::copy(outBegin, outEnd, std::back_inserter(asianText));

	std::string text = "j" + asianText;

	typedef lexertl::basic_utf8_in_iterator<const char*, uint32_t> Utf8IntputIterator;
	const char  *cStart = text.data(), *cEnd = text.data() + 1;//stop at the Asian char
	Utf8IntputIterator uStart(cStart, cEnd), uEnd(cEnd, cEnd);

	std::for_each(uStart, uEnd, [](const uint32_t& ch){
		std::cout << ch << std::endl;
	});

The above loop is passing uEnd iterator and the program eventually crashes.

**Comment by dboer** [comment]
To get the internal state to be the same (and the example to work) one could do something like:
Utf8IntputIterator uStart(cStart, cEnd), uEnd(cEnd, cEnd + 1);
This forces uEnd to compute it's internal state but I don't think this is the way to use the iterators.

**Comment by BenHanson** [comment]
Just picked up your issue. I will resolve this soon.

**Comment by BenHanson** [comment]
Now fixed.

**Comment by dboer** [comment]
Thank you!
