### ISSUE TITLE
minimise() doesn't compile

### ISSUE THREAD

**Issue by Anteru** [BenHanson/lexertl#17]
I just updated to lexertl 1.1 and noticed that `minimise()` does not compile. The first call:

    const id_type dfas_ = static_cast<id_type>(_internals.
            _dfa->size());

cannot use `->` because `_dfa` is not a pointer. Next, `id_type_vector *dfa_ = _internals._dfa[i_];` also fails. The rest seems fine.

**Comment by BenHanson** [comment]
Thanks for reporting this, this is now fixed. The 11 in lexertl11 refers to C++11!
