### ISSUE TITLE
LexerTL doesn’t recover correctly from an UTF-8 encoding error.

### ISSUE THREAD

**Issue by kaizawa** [BenHanson/lexertl#21]
Hi Ben,

First of all, thank you very much for writing a great tool. It's really useful and meets our requirements.

While writing parser program which reads utf8 file and tokenize contents, I saw an unexpected behavior.
If utf8 text file has illegal char, LexerTL doesn't recover correctly and continue to report incorrect position of token.
Please see following sample program. I also attached text file whose name is "hoge.txt".
This text file include '0x96' at offset of 3. 0x96 is  DASH char in CP1252, but it's unmapped in UTF-8.
Though it's illegal char, I expected LexerTL regards it as unknown single byte char, and subsequent token can be extracted correctly. But actually, it treats it as double byte char and it results in getting wrong position of subsequent tokens.

Here's a expected out put from sample program.
Id: 2, position=0, len=3
Id: 7, position=3, len=1
Id: 2, position=4, len=3
Id: 6, position=7, len=1
Id: 2, position=8, len=3

But actually, I got following output.
Id: 2, position=0, len=3
Id: 7, position=3, len=2  <== Length is 2.
Id: 2, position=5, len=3  <== position is shifted
Id: 6, position=8, len=1
Id: 2, position=9, len=3

Could you please fix this and make it recover even input text file has illegal char?

Thanks,
Kazuyoshi Aizawa

```
#include <iostream>
#include <fstream>
#include <string>
#include <boost/locale/info.hpp>
#include <lexertl/generator.hpp>
#include <lexertl/lookup.hpp>
#include <lexertl/utf_iterators.hpp>
#include <lexertl/state_machine.hpp>
#include <lexertl/generator.hpp>
#include <lexertl/iterator.hpp>

typedef lexertl::basic_utf8_in_iterator<const char*, uint32_t> Utf8Itr;

int main() {

	lexertl::basic_rules<char, uint32_t> rules(lexertl::icase);
	lexertl::basic_state_machine<uint32_t> sm;

	std::ifstream ifs("C:/hoge.txt");
	std::string input;
	std::getline(ifs, input);

	Utf8Itr start(input.c_str() + input.length(), input.c_str() + input.length());
	Utf8Itr end(input.c_str() + input.length(), input.c_str() + input.length());

	lexertl::match_results<lexertl::basic_utf8_in_iterator<const char*, uint32_t>> results(start, end);

	rules.push("can", 1);
	rules.push("cmd", 2);
	rules.push("\\s+", 6);
	rules.push(".", 7);

	lexertl::basic_generator < lexertl::basic_rules<char, uint32_t>, lexertl::basic_state_machine<uint32_t> >::build(rules, sm);

	results.start = results.end = Utf8Itr(input.c_str(), input.c_str() + input.length());
	sm.minimise();

	size_t position = 0;
	size_t tokenLen = 0;

	lexertl::basic_utf8_out_iterator<Utf8Itr> base(results.start, results.end);

	results.state = 0;
	lexertl::lookup(sm, results);

	while (results.id != 0) {
		lexertl::basic_utf8_out_iterator<Utf8Itr> start(results.start, results.end);
		lexertl::basic_utf8_out_iterator<Utf8Itr> end(results.end, results.end);

		tokenLen = static_cast<size_t>(std::distance(start, end));
		std::cout << "Id: " << results.id << ", position=" << position
			<< ", len=" << tokenLen << std::endl;

		position = static_cast<size_t>(std::distance(base, end));

		lexertl::lookup(sm, results);
	}
}
```

[hoge.txt](https://github.com/BenHanson/lexertl/files/399653/hoge.txt)

**Comment by BenHanson** [comment]
UTF-8 is described here: https://en.wikipedia.org/wiki/UTF-8#History

I dumped out your file as binary:

0b01100011 'c'
0b01101101 'm'
0b01100100 'd'
0b11100011 'ã'
0b10000010 '‚'
0b10110011 '³'
0b01100011 'c'

etc.

The best I could do is stop reading bytes when I hit a char that does not start with 0b10 as part of a malformed sequence. This would give you:

Id: 2, position=0, len=3
Id: 7, position=3, len=3
Id: 2, position=6, len=3

etc.

Beyond that, I'm not sure what kind of heuristic you would want for error correction.

**Comment by kaizawa** [comment]
Thank you for the reply and sorry for my late response.

With your solution, lexertl will give up tokenizing subsequent input? or just skip byte in question and continue to tokenize rest of input?

Solution I have in mind  is to map illegal byte to private area of unicode codepoint(e.g. U-F0000000).
And treat this special codepoint as single byte char in utf8 while processing output.

utf_inerators.hpp
113a114,117
>         case 0:
>             _end = _it;
>             ch_ |= 0xf0000000;
>             break;
264c268
<         return ch_ < 0x80 ? 1 :
---
>         return ch_ < 0x80 || ch_ & 0xf0000000 ? 1 :
486a491
> 

This change give me expected results.
Can it be applicable?

**Comment by BenHanson** [comment]
I am changing the len() function to return 1 when it comes across an unknown bit pattern that starts a sequence and I'm also changing the next() function to bail early if the high bit is not set when it should be.
