### ISSUE TITLE
LexerTL doesn’t recover correctly from an UTF-8 encoding error(2nd post)

### ISSUE THREAD

**Issue by kaizawa** [BenHanson/lexertl#22]
Hi,

Thank you for the prompt action for my request(issue#21)
And I'm sorry not to have responded timely.

I tried to run my sample program with new code, but result was same.
An illegal utf-8 char is calculated as 2 byte and position is shifted unexpectedly.

I just noticed previously uploaded sample text file(hoge.txt) doesn't include illegal utf-8 char.
I'm sorry about that. 
It seems the illegal byte in text file was converted while uploading to github.
This time I upload zip file which include actual text file, so that you can simulate the situation with sample program that I pasted in issue#21.

[hoge.zip](https://github.com/BenHanson/lexertl/files/448705/hoge.zip)
(you can see 0x96 at offset of 3)

From my debugging, the problem persists because len() function of basic_utf8_out_iterator class return 2 for 0x00000096, and next() function of basic_utf8_out_iterator generates 0xc296 as a result of conversion from UTF32 to UTF8.

In my solution, I temporary converted 0x96 to 0xf0000096 in next() function of basic_utf8_in_iterator class, and made len() function of basic_utf8_out_iterator return 1, if input has 0xF0000000 bit set. So that next() function of basic_utf8_out_iterator doesn't perform unnecessary conversion. (I mean keep 0x96 as it is with length of 1)

Thanks,
Kazuyoshi

**Comment by BenHanson** [comment]
Sorry, I don't think I can help with this problem. The utf8 iterators are simple examples based on http://utfcpp.sourceforge.net/

In my understanding, UTF-8 is merely a simple encoding mecanism as described at https://en.wikipedia.org/wiki/UTF-8#Description

If you have invalid Unicode as input, then detecting and/or correcting that is an entirely different topic and not one I have the time or inclination to explore. I don't know if http://site.icu-project.org/ can offer you something more useful.

I'm sorry I can't be of more help.
